# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "requests",
# ]
# ///

import sys
from pathlib import Path

import requests

# Minecraft and loader configuration
MINECRAFT_VERSION = "1.21.9"
LOADER = "fabric"

# List of mod slugs to download
MOD_LIST = [
    "lithium",
    "krypton",
    "fabric-api",
    "chunky",
]

# Modrinth API base URL
API_BASE = "https://api.modrinth.com/v2"
USER_AGENT = "yakub/minecraft-server-docker/1.0 (generate_mods.py)"


def get_mod_download_url(slug: str, minecraft_version: str, loader: str) -> str | None:
    """
    Fetch the download URL for the latest version of a mod from Modrinth.

    Args:
        slug: The mod's slug (e.g., "lithium", "fabric-api")
        minecraft_version: Target Minecraft version (e.g., "1.21.3")
        loader: Mod loader type (e.g., "fabric")

    Returns:
        Download URL string, or None if no suitable version found
    """
    url = f"{API_BASE}/project/{slug}/version"
    params = {
        "loaders": f'["{loader}"]',
        "game_versions": f'["{minecraft_version}"]',
    }
    headers = {
        "User-Agent": USER_AGENT,
    }

    try:
        response = requests.get(url, params=params, headers=headers, timeout=10)
        response.raise_for_status()

        versions = response.json()

        if not versions:
            print(f"Warning: No versions found for {slug} (MC {minecraft_version}, {loader})", file=sys.stderr)
            return None

        # Get the first (latest) version
        latest_version = versions[0]

        # Find the primary file
        files = latest_version.get("files", [])
        primary_file = next((f for f in files if f.get("primary", False)), None)

        if not primary_file and files:
            # If no primary file, use the first one
            primary_file = files[0]

        if primary_file:
            download_url = primary_file["url"]
            filename = primary_file["filename"]
            version_number = latest_version.get("version_number", "unknown")
            print(f"✓ {slug} v{version_number} -> {filename}", file=sys.stderr)
            return download_url
        else:
            print(f"Warning: No files found for {slug}", file=sys.stderr)
            return None

    except requests.RequestException as e:
        print(f"Error fetching {slug}: {e}", file=sys.stderr)
        return None


def main() -> None:
    """Generate build/mods.txt with download URLs from Modrinth."""
    print(f"Fetching mod URLs for Minecraft {MINECRAFT_VERSION} ({LOADER})...", file=sys.stderr)
    print(file=sys.stderr)

    urls = []

    for mod_slug in MOD_LIST:
        url = get_mod_download_url(mod_slug, MINECRAFT_VERSION, LOADER)
        if url:
            urls.append(url)

    print(file=sys.stderr)
    print(f"Found {len(urls)}/{len(MOD_LIST)} mods", file=sys.stderr)

    # Write to build/mods.txt
    output_path = Path(__file__).parent / "build" / "mods.txt"
    output_path.parent.mkdir(exist_ok=True)

    with output_path.open("w") as f:
        f.write("# Generated mod list for Fabric Minecraft Server\n")
        f.write(f"# Minecraft version: {MINECRAFT_VERSION}\n")
        f.write(f"# Loader: {LOADER}\n")
        f.write("#\n")
        f.write("# Do not edit this file manually - regenerate with: python generate_mods.py\n")
        f.write("\n")

        for url in urls:
            f.write(f"{url}\n")

    print(f"\n✓ Written {len(urls)} mod URLs to {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
